resource "helm_release" "mariadb" {
  name      = "database"
  namespace = kubernetes_namespace.mediawiki.metadata[0].name
  chart     = "./mediawiki-mariadb-chart"

  values = [
    yamlencode({
      mariadb = {
        rootUser = {
          password = var.db_root_password
        }
        db = {
          name     = var.db_name
          user     = var.db_user
          password = var.db_password
        }
      }
      service = {
        type = "ClusterIP"
        port = 3306
      }
      fullnameOverride = "database"
    })
  ]

  depends_on = [aws_eks_node_group.default]
}