resource "helm_release" "mediawiki" {
  name      = "mediawiki"
  namespace = kubernetes_namespace.mediawiki.metadata[0].name
  chart     = "./mediawiki-chart"

  values = [
    yamlencode({
      image = {
        repository = "aks-mediawiki/mediawiki"  # change if needed
        tag        = "latest"
        pullPolicy = "IfNotPresent"
      }
      service = {
        type = "LoadBalancer"
        port = 80
      }
      env = [
        {
          name  = "MW_DB_HOST"
          value = "database"
        },
        {
          name  = "MW_DB_PORT"
          value = "3306"
        },
        {
          name = "MW_DB_NAME"
          valueFrom = {
            secretKeyRef = {
              name = "mediawiki-db"
              key  = "name"
            }
          }
        },
        {
          name = "MW_DB_USER"
          valueFrom = {
            secretKeyRef = {
              name = "mediawiki-db"
              key  = "user"
            }
          }
        },
        {
          name = "MW_DB_PASSWORD"
          valueFrom = {
            secretKeyRef = {
              name = "mediawiki-db"
              key  = "password"
            }
          }
        }
      ]
      extraManifests = [
        {
          apiVersion = "v1"
          kind       = "Secret"
          metadata = {
            name = "mediawiki-db"
          }
          type       = "Opaque"
          stringData = {
            name     = var.db_name
            user     = var.db_user
            password = var.db_password
          }
        }
      ]
    })
  ]

  depends_on = [helm_release.mariadb]
}
